### ISSUE TITLE
Error installing node-sqlite3 on macOS 10.14 and Xcode 10

### ISSUE THREAD

**Issue by mario-grgic** [mapbox/node-sqlite3#1050]
Tried to install node-sqlite3 and got:

```
$ npm install -s node-sqlite3
  CXX(target) Release/obj.target/node_sqlite3/src/third_party/CodingConv/encodeutil.o
../src/third_party/CodingConv/encodeutil.cpp:179:31: error: use of undeclared identifier 'LC_ALL'
        string curLocale = setlocale(LC_ALL,NULL);
                                     ^
../src/third_party/CodingConv/encodeutil.cpp:180:12: error: use of undeclared identifier 'LC_ALL'
        setlocale(LC_ALL,"chs");
                  ^
../src/third_party/CodingConv/encodeutil.cpp:188:12: error: use of undeclared identifier 'LC_ALL'; did you mean 'P_ALL'?
        setlocale(LC_ALL,curLocale.c_str());
                  ^~~~~~
                  P_ALL
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/wait.h:80:2: note: 
      'P_ALL' declared here
        P_ALL,
        ^
../src/third_party/CodingConv/encodeutil.cpp:197:31: error: use of undeclared identifier 'LC_ALL'
        string curLocale = setlocale(LC_ALL,NULL);
                                     ^
../src/third_party/CodingConv/encodeutil.cpp:198:12: error: use of undeclared identifier 'LC_ALL'
        setlocale(LC_ALL,"chs");
                  ^
../src/third_party/CodingConv/encodeutil.cpp:206:12: error: use of undeclared identifier 'LC_ALL'; did you mean 'P_ALL'?
        setlocale(LC_ALL,curLocale.c_str());
                  ^~~~~~
                  P_ALL
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/wait.h:80:2: note: 
      'P_ALL' declared here
        P_ALL,
        ^
6 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/third_party/CodingConv/encodeutil.o] Error 1
```

This is on macOS 10.14 Mojave, Xcode 10, node v8.11.1 and npm 6.4.1.

**Comment by magneticchen** [comment]
Also got this error.

**Comment by magneticchen** [comment]
fixed in new version confirmed.

**Comment by DOSputin** [comment]
> fixed in new version confirmed.
Can you provide more context?

The issue seems to persist here @ macOS 10.13.6 High Sierra, Xcode 10, node v11.2.0, npm  v6.5.0

**Comment by mario-grgic** [comment]
If I clone this repo and `make` it all builds correctly. If I do ```npm install node-sqlite3``` it still fails with the above error.

Installing `ninja` of course made no difference. The errors are complaining about undefined `LC_ALL` macro.

**Comment by atsepkov** [comment]
Same error on High Sierra 10.13.6, node v8.12 when installing from npm.

**Comment by atsepkov** [comment]
So the issue is that node-sqlite3 in npm is a different package that seems to have deceptively similar name to this repo. The npm package for this repo is sqlite3, not node-sqlite3.

**Comment by mario-grgic** [comment]
> So the issue is that node-sqlite3 in npm is a different package that seems to have deceptively similar name to this repo. The npm package for this repo is sqlite3, not node-sqlite3.

Wow, that's horrible. Especially since this project's GitHub repo is called node-sqlite3. And yes, npm install sqlite3 works.
